version: '3'
services:
  python3_web:
    container_name: printer_app
    build:
        context: ./
        dockerfile: Dockerfile
#    image: syukurdocker/thermal_printer:latest
#    devices:
#        - /dev/usb/lp0:/dev/usb/lp0
    environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=syukur123***
        - POSTGRES_HOST=192.168.0.88
        - POSTGRES_PORT=5432
        - POSTGRES_DB=PerniagaanDonut_dev
    restart: always
    ports:
        - '5001:5000'
