version: '3'
services:
  python3_web:
    container_name: printer_app
    build:
        context: ./
        dockerfile: Dockerfile
#    image: syukurdocker/thermal_printer:latest
#    devices:
#        - /dev/usb/lp0:/dev/usb/lp0
    restart: always
    ports:
        - '5001:5000'
