version: '3.3'
services:
  app:
    container_name: printer_app
#    build:
#        context: ./
#        dockerfile: Dockerfile
    image: syukurdocker/thermal_printer:latest
    devices:
        - /dev/usb/lp0:/dev/usb/lp0
    restart: always
    ports:
        - '5000:5000'
